version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./static:/usr/share/nginx/html/static  # Shared volume for static files
    networks:
      - nginx_net
    depends_on:
      - flask_app

  flask_app:
    build: ./flask_app
    volumes:
      - ./static:/app/static  # Mount static folder to Flask
    environment:
      - FLASK_ENV=development
    network_mode: host  # Give Flask access to the host network for WebTorrent
    ports:
      - "443:443"
    command: >
      bash -c "gunicorn --bind 0.0.0.0:5000 --workers 3 --worker-class gevent app:app"

networks:
  nginx_net:
    driver: bridge
