version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./static:/usr/share/nginx/html/static  # Shared volume for static files
    networks:
      - nginx_net  # Attach Nginx to the bridge network
    depends_on:
      - flask_app

  flask_app:
    build: ./flask_app
    volumes:
      - ./static:/app/static  # Mount static folder to Flask
    environment:
      - FLASK_ENV=development
    networks:
      - nginx_net  # Attach Flask to the Nginx network
      # Use "host" without an alias
      - host  # Attach Flask to the host network for WebTorrent

networks:
  nginx_net:  # Custom bridge network for Nginx and Flask
    driver: bridge
  host:  # Host network for Flask (needed by WebTorrent)
    external: true  # Use the existing Docker host network
