version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./static:/usr/share/nginx/html/static  # Shared volume for static files
    depends_on:
      - flask_app
    environment:
      - HOST_IP=158.69.59.168  # Replace this with the actual host IP
    command: >
      sh -c "while ! curl http://$HOST_IP:5000; do sleep 1; done && nginx -g 'daemon off;'"

  flask_app:
    build: ./flask_app
    volumes:
      - ./static:/app/static  # Mount static folder to Flask
    environment:
      - FLASK_ENV=development
    network_mode: host  # Give Flask access to the host network for WebTorrent
    ports:
      - "5000:5000"
    command: >
      bash -c "gunicorn --bind 0.0.0.0:5000 --timeout 120 --workers 9 --worker-class gevent app:app"
