version: '3'

services:
  nginx:
    build: ./nginx  # Your Nginx Dockerfile should be inside ./nginx directory
    ports:
      - "6881-6889:6881-6889"  # Torrenting ports
      - "443:443"
    volumes:
      - ./static:/usr/share/nginx/html/static  # Mount the static folder to Nginx for serving static files
    depends_on:
      - flask_app

  flask_app:
    build: ./flask_app  # Your Flask Dockerfile should be inside ./flask_app directory
    volumes:
      - ./static:/app/static  # Mount the static folder to Flask for static file access
    environment:
      - FLASK_ENV=development  # Or production

volumes:
  shared_files:  # This can be omitted unless used elsewhere
