version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./static:/usr/share/nginx/html/static  # Shared volume for static files
    network_mode: host  # Use host network mode for Nginx as well
    depends_on:
      - flask_app
    command: >
      sh -c "while ! curl http://localhost:5000; do sleep 1; done && nginx -g 'daemon off;'"
    
  flask_app:
    build: ./flask_app
    volumes:
      - ./static:/app/static  # Mount static folder to Flask
    environment:
      - FLASK_ENV=development
    network_mode: host  # Host network for Flask
    ports:
      - "5000:5000"
    command: > # bash -c "gunicorn --bind 0.0.0.0:5000 --timeout 120 --workers 9 --worker-class gevent app:app"
      bash -c "gunicorn --bind 0.0.0.0:5000 --timeout 120 --workers 9 --worker-class gevent --certfile=/app/ssl/self-signed.crt --keyfile=/app/ssl/self-signed.key app:app"
