version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - shared_files:/usr/share/nginx/html  # Shared volume for static files
    depends_on:
      - flask_app

  flask_app:
    build: ./flask_app  # Your Flask Dockerfile should be inside ./flask_app directory
    volumes:
      - shared_files:/app/static            # Mount shared volume for static files
    environment:
      - FLASK_ENV=development  # Or production

volumes:
  shared_files:
